# Generated by Django 3.1.2 on 2020-10-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_background',
            field=models.ImageField(blank=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, upload_to='events'),
        ),
    ]
