# Generated by Django 3.1.2 on 2020-10-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='karma',
            field=models.IntegerField(choices=[(0, 'Neutral karma'), (1, 'Good karma'), (-1, 'Bad karma')], default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
