# Generated by Django 3.1.2 on 2020-10-17 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20201017_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_type', models.CharField(choices=[('age', 'Age'), ('education', 'Education'), ('child', 'Children'), ('sex', 'Sex'), ('income', 'Income')], default='', max_length=120)),
                ('variable_value', models.CharField(default='', max_length=12)),
                ('variable_odds', models.FloatField(default=0)),
                ('Choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.choice')),
            ],
        ),
    ]
