# Generated by Django 3.1.2 on 2020-10-17 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odds',
            name='Choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
