# Generated by Django 3.1.2 on 2020-10-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20201017_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
