# Generated by Django 3.1.2 on 2020-10-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_choice_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odds',
            name='variable_odds',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='odds',
            name='variable_value',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
